### ISSUE TITLE
Warlords of Draenor changes

### ISSUE THREAD

**Issue by Rainrider** [Rainrider/DRData-1.0#1]
### Hunter
- [ ] Knock-back effect from Powershot
- [ ] Stun from tenacity pets' Charge (does is really share a DR?)
### Monk
- [ ] Breath of Fire (glyphed) (Incapacitate like in forum or Disorient like in tooltip?)
### Shaman
- [ ] Stun from Earthquake (right category?)
### Warrior
- [ ] Stun from Dragon Roar (right category?)

**Comment by vendethiel** [comment]
@Rainrider as discussed elsewhere - Do you want me to use this verison (and PR) or should I just fork it?

**Comment by Rainrider** [comment]
Fork and adapt to your needs pls, I have no use for DRData right now, so I wouldn't spend time on keeping it up-to-date.
